### ISSUE TITLE
card消息模块

### ISSUE THREAD

**Issue by sunsou1** [larksuite/appframework-java#11]
1. 多语言支持，这边看官方文档
![image](https://user-images.githubusercontent.com/23651876/84636303-0757c780-af27-11ea-880d-44abbc2f1afd.png)
官方文档是i18n_elements，sdk里是i18nElements。
2. 消息卡片更新时，采用return方式，更新后中文会乱码，这块能麻烦看看吗？

**Comment by sunsou1** [comment]
第二个问题好像需要在return的header的 Content-Type 增加application/json; charset=utf-8

**Comment by sunsou1** [comment]
![image](https://user-images.githubusercontent.com/23651876/84727452-a6310200-afc1-11ea-8f34-e81874a06df2.png)
第二个问题我这边测试了下，再这个文件返回resp时加上这个就可以了。

**Comment by sunsou1** [comment]
resp.setContentType("application/json;charset=UTF-8");
你好 这边测试了下 再返回的时候加上这个就可以了。

**Comment by xionghan00** [comment]
能否为这两个问题提个pr？

**Comment by xionghan00** [comment]
1.0.8 released
