### ISSUE TITLE
消息卡片交互，更新card中文标题乱码

### ISSUE THREAD

**Issue by fuubo** [larksuite/appframework-java#13]
`@CardAction(methodName = "TestCard.dp")
    public Card onCardEvent(CardEvent event) {
        return new Card(new Config(true), new Header(new Text(Text.Mode.PLAIN_TEXT, "中文标题"), TemplateColor.GREEN));
    }`

**Comment by xionghan00** [comment]
应该是同一个问题     https://github.com/larksuite/appframework-java/issues/11
